-- MySQL Script generated by MySQL Workbench
-- Fri Sep 17 20:02:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personal` (
  `idpersonal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(500) NOT NULL,
  `apellido` VARCHAR(500) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(500) NOT NULL,
  `email` VARCHAR(500) NOT NULL,
  `fechanacimiento` DATE NOT NULL,
  PRIMARY KEY (`idpersonal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipologro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipologro` (
  `idtipologro` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idtipologro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`logro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`logro` (
  `idlogro` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(500) NOT NULL,
  `idtipologro` INT NOT NULL,
  `idpresonal` INT NOT NULL,
  PRIMARY KEY (`idlogro`),
  INDEX `fk_tipo_Logros_idx` (`idtipologro` ASC) VISIBLE,
  INDEX `fk_personal_logros_idx` (`idpresonal` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_Logros`
    FOREIGN KEY (`idtipologro`)
    REFERENCES `mydb`.`tipologro` (`idtipologro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_logros`
    FOREIGN KEY (`idpresonal`)
    REFERENCES `mydb`.`personal` (`idpersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
